/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description 503 while shutting down or when the database is unreachable.
         */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account with email and password */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with a Google Identity Services ID token
         * @description Only mounted when the server has `GOOGLE_CLIENT_ID` set; 404 otherwise.
         */
        post: operations["loginWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session and clear the cookie
         * @description Public, so a client with an expired session can still clear its cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vacancies */
        get: operations["listVacancies"];
        put?: never;
        /**
         * Create a vacancy
         * @description `company_name` is resolved to a company (created if it doesn't exist)
         *     when `company_id` is not given.
         */
        post: operations["createVacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        /** Get a vacancy */
        get: operations["getVacancy"];
        put?: never;
        post?: never;
        /** Soft-delete a vacancy */
        delete: operations["deleteVacancy"];
        options?: never;
        head?: never;
        /**
         * Update some of a vacancy's fields
         * @description JSON merge-patch semantics: a field left out is unchanged, `null`
         *     clears it, a value sets it. `title` can't be cleared.
         */
        patch: operations["updateVacancy"];
        trace?: never;
    };
    "/vacancies/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo a soft delete */
        post: operations["restoreVacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications */
        get: operations["listApplications"];
        put?: never;
        /**
         * Apply to a vacancy
         * @description Adds the card at the bottom of its starting column.
         */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active applications grouped by stage
         * @description A stage with no applications is left out of the object.
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        /** Get an application */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        /** Soft-delete an application */
        delete: operations["deleteApplication"];
        options?: never;
        head?: never;
        /**
         * Update priority and/or notes
         * @description JSON merge-patch semantics: a field left out is unchanged, `null`
         *     clears `notes`, a value sets it. `priority` can't be null.
         */
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/applications/{id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Move an application to another stage
         * @description Appends the card to the bottom of the target column and records a `stage_change` event.
         */
        patch: operations["changeApplicationStage"];
        trace?: never;
    };
    "/applications/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Drag a card on the board
         * @description Places the card between `after_id` and `before_id` (either may be
         *     omitted at a column edge) in `stage`. A change of stage records a
         *     `stage_change` event; reordering within a column does not.
         */
        post: operations["moveApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @enum {string} */
            error: "validation_failed" | "unauthorized" | "unsupported_media_type" | "forbidden" | "not_found" | "conflict" | "internal_error";
            message: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name?: string | null;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        GoogleLoginRequest: {
            /** @description The `credential` Google Identity Services hands the frontend. */
            id_token: string;
        };
        User: {
            /** Format: int64 */
            id: number;
            email: string;
            display_name: string | null;
            locale: string;
            email_verified: boolean;
            /** @description False for accounts that only sign in with Google. */
            has_password: boolean;
        };
        Session: {
            user: components["schemas"]["User"];
            token: string;
            /** Format: date-time */
            expires_at: string;
        };
        /** @enum {string} */
        WorkMode: "onsite" | "hybrid" | "remote";
        /** @enum {string} */
        EmploymentType: "full_time" | "part_time" | "contract" | "internship";
        /** @enum {string} */
        SalaryPeriod: "hour" | "day" | "month" | "year";
        VacancyCreate: {
            /** Format: int64 */
            company_id?: number | null;
            /** @description Used when `company_id` is not given. */
            company_name?: string | null;
            title: string;
            url?: string | null;
            description?: string | null;
            location?: string | null;
            work_mode?: (string & components["schemas"]["WorkMode"]) | null;
            employment_type?: (string & components["schemas"]["EmploymentType"]) | null;
            language?: string | null;
            /** Format: int32 */
            salary_min?: number | null;
            /** Format: int32 */
            salary_max?: number | null;
            salary_currency?: string | null;
            salary_period?: (string & components["schemas"]["SalaryPeriod"]) | null;
            source?: string | null;
            /** Format: date */
            posted_at?: string | null;
        };
        VacancyPatch: {
            /** Format: int64 */
            company_id?: number | null;
            title?: string;
            url?: string | null;
            description?: string | null;
            location?: string | null;
            work_mode?: (string & components["schemas"]["WorkMode"]) | null;
            employment_type?: (string & components["schemas"]["EmploymentType"]) | null;
            language?: string | null;
            /** Format: int32 */
            salary_min?: number | null;
            /** Format: int32 */
            salary_max?: number | null;
            salary_currency?: string | null;
            salary_period?: (string & components["schemas"]["SalaryPeriod"]) | null;
            source?: string | null;
            /** Format: date */
            posted_at?: string | null;
        };
        Vacancy: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            user_id: number;
            /** Format: int64 */
            company_id?: number;
            title: string;
            url?: string;
            description?: string;
            location?: string;
            work_mode?: components["schemas"]["WorkMode"];
            employment_type?: components["schemas"]["EmploymentType"];
            language?: string;
            /** Format: int32 */
            salary_min?: number;
            /** Format: int32 */
            salary_max?: number;
            salary_currency?: string;
            salary_period?: components["schemas"]["SalaryPeriod"];
            source?: string;
            /** Format: date */
            posted_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        VacancyList: {
            items: components["schemas"]["Vacancy"][];
            /** Format: int64 */
            total: number;
        };
        /** @enum {string} */
        Stage: "saved" | "applied" | "screening" | "interview" | "final" | "offer" | "rejected" | "withdrawn";
        ApplyRequest: {
            /** Format: int64 */
            vacancy_id: number;
            /** @description Defaults to `saved`. */
            stage?: (string & components["schemas"]["Stage"]) | null;
        };
        UpdateApplicationRequest: {
            /** Format: int32 */
            priority?: number;
            notes?: string | null;
        };
        ChangeStageRequest: {
            to: components["schemas"]["Stage"];
        };
        MoveRequest: {
            stage: components["schemas"]["Stage"];
            /**
             * Format: int64
             * @description The card that should end up directly above this one.
             */
            after_id?: number | null;
            /**
             * Format: int64
             * @description The card that should end up directly below this one.
             */
            before_id?: number | null;
        };
        Application: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            user_id: number;
            /** Format: int64 */
            vacancy_id: number;
            stage: components["schemas"]["Stage"];
            /**
             * Format: double
             * @description Sort key within the stage column.
             */
            board_order: number;
            /** Format: int32 */
            priority: number;
            /** Format: date-time */
            applied_at?: string;
            /** Format: date-time */
            closed_at?: string;
            notes?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApplicationList: {
            items: components["schemas"]["Application"][];
            /** Format: int64 */
            total: number;
        };
        Board: {
            saved?: components["schemas"]["ApplicationColumn"];
            applied?: components["schemas"]["ApplicationColumn"];
            screening?: components["schemas"]["ApplicationColumn"];
            interview?: components["schemas"]["ApplicationColumn"];
            final?: components["schemas"]["ApplicationColumn"];
            offer?: components["schemas"]["ApplicationColumn"];
            rejected?: components["schemas"]["ApplicationColumn"];
            withdrawn?: components["schemas"]["ApplicationColumn"];
        };
        ApplicationColumn: components["schemas"]["Application"][];
    };
    responses: {
        /**
         * @description A new session. The token is also set as the HttpOnly `session` cookie;
         *     browser code should rely on the cookie rather than storing the token.
         */
        Session: {
            headers: {
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description The request is malformed or fails validation (`error` is `validation_failed`). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid session, or wrong credentials (`error` is `unauthorized`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource for this user (`error` is `not_found`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with current state (`error` is `conflict`). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body was not sent as `application/json` (`error` is `unsupported_media_type`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ID: number;
        Desc: boolean;
        /** @description Values outside 1..200 fall back to 50. */
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to receive traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: components["responses"]["Session"];
            400: components["responses"]["ValidationFailed"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    loginWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            /** @description Google sign-in is not configured on this server. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listVacancies: {
        parameters: {
            query?: {
                company_id?: number;
                salary_from?: number;
                /** @description Omit for any, `true` for vacancies with an active application, `false` for those without. */
                has_application?: boolean;
                /** @description Comma-separated. */
                work_mode?: components["schemas"]["WorkMode"][];
                /** @description Comma-separated. */
                employment_type?: components["schemas"]["EmploymentType"][];
                /** @description Comma-separated. */
                language?: string[];
                /** @description Comma-separated. */
                source?: string[];
                /** @description Matches title or description. */
                q?: string;
                /** @description Defaults to `created_at`, newest first. */
                sort?: "created_at" | "updated_at" | "posted_at" | "title" | "salary";
                desc?: components["parameters"]["Desc"];
                /** @description Values outside 1..200 fall back to 50. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of vacancies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyList"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyCreate"];
            };
        };
        responses: {
            /** @description The created vacancy. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            /** @description `company_id` is not one of this user's companies (`error` is `not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    getVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The vacancy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyPatch"];
            };
        };
        responses: {
            /** @description The updated vacancy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    restoreVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listApplications: {
        parameters: {
            query?: {
                company_id?: number;
                min_priority?: number;
                /** @description Comma-separated. */
                vacancy_id?: number[];
                /** @description Comma-separated. */
                tag_id?: number[];
                /** @description Comma-separated. */
                stage?: components["schemas"]["Stage"][];
                /** @description Matches vacancy title or company name. */
                q?: string;
                /** @description Defaults to `board`. */
                sort?: "board" | "created_at" | "updated_at" | "priority";
                desc?: components["parameters"]["Desc"];
                /** @description Values outside 1..200 fall back to 50. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of applications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationList"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description The created application. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Kanban board. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The application. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description The updated application. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    changeApplicationStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStageRequest"];
            };
        };
        responses: {
            /** @description The updated application. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    moveApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description The moved application. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
}
